"""032_add_oauth_device_codes_table

Revision ID: 137b48ae1497
Revises: f8a0d3e4c2b5
Create Date: 2026-05-08 23:24:42.304762

Migration 032: Add oauth_device_codes table for OAuth 2.0 device authorization grant
Tier 1: Additive - new table only, no modifications to existing schema

Required for CP10 P1 wrapper OAuth flow. Stores device/user code pairs for
terminal-friendly authentication (https://tools.ietf.org/html/rfc8628).

Schema:
- device_code: Primary key, UUID generated by server
- user_code: User-visible short code (e.g., "ABCD-EFGH")
- tenant_id: NULL until user approves at verification_uri
- expires_at: 10-minute TTL from creation
- approved_at: Timestamp when user confirmed authorization
- created_at: Row creation timestamp
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '137b48ae1497'
down_revision: Union[str, Sequence[str], None] = 'f8a0d3e4c2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add oauth_device_codes table."""
    
    op.execute("""
        CREATE TABLE memory_service.oauth_device_codes (
            device_code TEXT PRIMARY KEY,
            user_code TEXT UNIQUE NOT NULL,
            tenant_id UUID,
            expires_at TIMESTAMPTZ NOT NULL,
            approved_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    """)
    
    op.execute("""
        CREATE INDEX idx_oauth_device_user_code 
        ON memory_service.oauth_device_codes(user_code);
    """)


def downgrade() -> None:
    """Remove oauth_device_codes table."""
    
    op.execute("""
        DROP INDEX IF EXISTS memory_service.idx_oauth_device_user_code;
    """)
    
    op.execute("""
        DROP TABLE IF EXISTS memory_service.oauth_device_codes;
    """)
